/**
 * Property-based test for simple sentence structure
 * **Feature: optimized-lesson-types, Property 1, 2, 3: Simple sentence lessons validation**
 * **Validates: Requirements 1.1, 1.2, 1.3**
 */

const fc = require('fast-check');
const { generateContent } = require('../../src/services/CEFRContentService');

// Mock AIService to avoid actual API calls during testing
jest.mock('../../src/services/AIService', () => ({
  generateWithRetry: jest.fn()
}));

const AIService = require('../../src/services/AIService');

describe('Simple Sentence Structure Properties', () => {
  // Arbitraries for test data generation
  const cefrLevelArbitrary = fc.constantFrom('A1', 'A2', 'B1', 'B2', 'C1', 'C2');
  const languageArbitrary = fc.constantFrom('Spanish', 'French', 'German', 'Italian', 'Portuguese');
  const domainArbitrary = fc.constantFrom('personal', 'public', 'occupational', 'educational');
  const topicArbitrary = fc.string({ minLength: 5, maxLength: 50 });

  beforeEach(() => {
    jest.clearAllMocks();
  });

  /**
   * Property 1: Simple sentence lessons have exactly one question
   * For any simple sentence lesson generated by the system, the quiz_items array should contain exactly 1 question.
   */
  it('Property 1: should have exactly one question in quiz_items', async () => {
    await fc.assert(
      fc.asyncProperty(
        cefrLevelArbitrary,
        languageArbitrary,
        domainArbitrary,
        topicArbitrary,
        async (level, language, domain, topic) => {
          // Mock AI response for simple_sentence
          const mockResponse = {
            type: 'simple_sentence',
            sentence: 'Esta es una oración simple.',
            quiz_items: [
              {
                question: '¿Qué significa esta oración?',
                options: ['This is a simple sentence', 'That is complex', 'Here is nothing', 'Where is it'],
                correct_index: 0
              }
            ]
          };

          AIService.generateWithRetry.mockResolvedValue({
            json: mockResponse,
            usedSource: 'test'
          });

          const result = await generateContent(level, language, domain, topic, 'simple_sentence');
          
          // Validate exactly 1 question
          expect(result.content.quiz_items).toHaveLength(1);
          expect(result.content.type).toBe('simple_sentence');
        }
      ),
      { numRuns: 100 }
    );
  });

  /**
   * Property 2: Simple sentence context is minimal
   * For any simple sentence lesson, the sentence field should contain at most one sentence 
   * (verified by counting sentence-ending punctuation: . ! ?).
   */
  it('Property 2: should have minimal context (at most one sentence)', async () => {
    await fc.assert(
      fc.asyncProperty(
        cefrLevelArbitrary,
        languageArbitrary,
        domainArbitrary,
        topicArbitrary,
        fc.string({ minLength: 10, maxLength: 100 }).filter(s => !s.match(/[.!?]/)), // Generate sentence without punctuation
        async (level, language, domain, topic, sentenceText) => {
          // Ensure the sentence ends with proper punctuation (only one)
          const cleanSentence = sentenceText.trim() + '.';
          
          // Mock AI response with the generated sentence
          const mockResponse = {
            type: 'simple_sentence',
            sentence: cleanSentence,
            quiz_items: [
              {
                question: 'Test question?',
                options: ['Option 1', 'Option 2', 'Option 3', 'Option 4'],
                correct_index: 0
              }
            ]
          };

          AIService.generateWithRetry.mockResolvedValue({
            json: mockResponse,
            usedSource: 'test'
          });

          const result = await generateContent(level, language, domain, topic, 'simple_sentence');
          
          // Count sentence-ending punctuation
          const sentence = result.content.sentence;
          const sentenceEndingCount = (sentence.match(/[.!?]/g) || []).length;
          
          // Should have at most 1 sentence (1 ending punctuation)
          expect(sentenceEndingCount).toBeLessThanOrEqual(1);
          expect(sentence).toBeDefined();
          expect(sentence.length).toBeGreaterThan(0);
        }
      ),
      { numRuns: 100 }
    );
  });

  /**
   * Property 3: Simple sentence questions have four options
   * For any simple sentence lesson, each question in quiz_items should have exactly 4 options in the options array.
   */
  it('Property 3: should have exactly 4 options for the question', async () => {
    await fc.assert(
      fc.asyncProperty(
        cefrLevelArbitrary,
        languageArbitrary,
        domainArbitrary,
        topicArbitrary,
        async (level, language, domain, topic) => {
          // Mock AI response with 4 options
          const mockResponse = {
            type: 'simple_sentence',
            sentence: 'Test sentence in target language.',
            quiz_items: [
              {
                question: 'What does this mean?',
                options: ['Option A', 'Option B', 'Option C', 'Option D'],
                correct_index: 0
              }
            ]
          };

          AIService.generateWithRetry.mockResolvedValue({
            json: mockResponse,
            usedSource: 'test'
          });

          const result = await generateContent(level, language, domain, topic, 'simple_sentence');
          
          // Validate exactly 4 options
          expect(result.content.quiz_items[0].options).toHaveLength(4);
          expect(Array.isArray(result.content.quiz_items[0].options)).toBe(true);
        }
      ),
      { numRuns: 100 }
    );
  });

  /**
   * Combined property: Simple sentence lessons should have all required fields
   */
  it('should have all required fields for simple_sentence lessons', async () => {
    await fc.assert(
      fc.asyncProperty(
        cefrLevelArbitrary,
        languageArbitrary,
        domainArbitrary,
        topicArbitrary,
        async (level, language, domain, topic) => {
          // Mock complete simple_sentence response
          const mockResponse = {
            type: 'simple_sentence',
            sentence: 'Complete test sentence.',
            quiz_items: [
              {
                question: 'Test question?',
                options: ['A', 'B', 'C', 'D'],
                correct_index: 0
              }
            ]
          };

          AIService.generateWithRetry.mockResolvedValue({
            json: mockResponse,
            usedSource: 'test'
          });

          const result = await generateContent(level, language, domain, topic, 'simple_sentence');
          
          // Validate structure
          expect(result.content).toHaveProperty('type');
          expect(result.content).toHaveProperty('sentence');
          expect(result.content).toHaveProperty('quiz_items');
          expect(result.content.type).toBe('simple_sentence');
          
          // Validate quiz_items structure
          const quizItem = result.content.quiz_items[0];
          expect(quizItem).toHaveProperty('question');
          expect(quizItem).toHaveProperty('options');
          expect(quizItem).toHaveProperty('correct_index');
          expect(typeof quizItem.correct_index).toBe('number');
          expect(quizItem.correct_index).toBeGreaterThanOrEqual(0);
          expect(quizItem.correct_index).toBeLessThan(4);
        }
      ),
      { numRuns: 100 }
    );
  });

  /**
   * Property: Simple sentence lessons should work across all CEFR levels
   */
  it('should generate valid simple_sentence lessons for all CEFR levels', async () => {
    await fc.assert(
      fc.asyncProperty(
        cefrLevelArbitrary,
        languageArbitrary,
        domainArbitrary,
        topicArbitrary,
        async (level, language, domain, topic) => {
          // Mock response
          const mockResponse = {
            type: 'simple_sentence',
            sentence: `${level} level sentence in ${language}.`,
            quiz_items: [
              {
                question: 'Question?',
                options: ['A', 'B', 'C', 'D'],
                correct_index: 0
              }
            ]
          };

          AIService.generateWithRetry.mockResolvedValue({
            json: mockResponse,
            usedSource: 'test'
          });

          const result = await generateContent(level, language, domain, topic, 'simple_sentence');
          
          // Validate metadata
          expect(result.metadata.level).toBe(level);
          expect(result.metadata.language).toBe(language);
          expect(result.metadata.content_type).toBe('simple_sentence');
          
          // Validate content
          expect(result.content.type).toBe('simple_sentence');
          expect(result.content.quiz_items).toHaveLength(1);
          expect(result.content.quiz_items[0].options).toHaveLength(4);
        }
      ),
      { numRuns: 100 }
    );
  });

  /**
   * Property: Sentence field should not be empty or undefined
   */
  it('should always have a non-empty sentence field', async () => {
    await fc.assert(
      fc.asyncProperty(
        cefrLevelArbitrary,
        languageArbitrary,
        domainArbitrary,
        topicArbitrary,
        async (level, language, domain, topic) => {
          // Mock response with sentence
          const mockResponse = {
            type: 'simple_sentence',
            sentence: 'Non-empty sentence content.',
            quiz_items: [
              {
                question: 'Q?',
                options: ['A', 'B', 'C', 'D'],
                correct_index: 0
              }
            ]
          };

          AIService.generateWithRetry.mockResolvedValue({
            json: mockResponse,
            usedSource: 'test'
          });

          const result = await generateContent(level, language, domain, topic, 'simple_sentence');
          
          expect(result.content.sentence).toBeDefined();
          expect(result.content.sentence).not.toBe('');
          expect(typeof result.content.sentence).toBe('string');
          expect(result.content.sentence.length).toBeGreaterThan(0);
        }
      ),
      { numRuns: 100 }
    );
  });
});
